### PR TITLE
Medical device template developed by GE Healthcare

### PR DESCRIPTION
**Pull request by jpschaaf**
Work by Matthew Clapham, Valery Berestetsky, Dan Birtwhistle, and Jonathan Schaaf (all at GE Healthcare).

### CODE REVIEW

**Comment by jegeib** [comment]
Content under review for inclusion with TMT

**Comment by parulgarg** [comment]
@jpschaaf  For testing purpose , this needs to be merged to dev first. Can you raise a PR with required changed to be merged to dev ? We will test it out and then merge to master , if it all passes.

**Comment by parulgarg** [comment]
@jpschaaf For testing purpose , this needs to be merged to dev first. Can you raise a PR with required changed to be merged to dev ? We will test it out and then merge to master , if it all passes.

**Comment by jpschaaf** [comment]
It might be a few days before I get to it, but I will do as requested.

**Comment by parulgarg** [comment]
@jpschaaf I have merged the template to Dev branch and we are currently in process of verifying it. As and when you have time , please check to see if it looks good on the dev branch.

https://github.com/Microsoft/threat-modeling-templates/pull/24

**Pull request closed without merging**
